version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: always
    env_file:
      - .flaskenv
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .flaskenv
    volumes:
      #- db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 0s

  redis:
    image: "redis/redis-stack:latest"
    restart: always
    env_file:
      - .flaskenv
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    ports:
      - "${REDIS_PORT}:6379"

#volumes:
#  db_data: